// frontend/src/views/PYQPageView.vue
<template>
  <Header />
  <PYQup />
  <PyqOverview />
  <TextTable />
  <BiharSyllabusComponent />
  <PyqSyPdf />
  <Footer />
</template>

<script>
import Header from "@/components/Homepage/HeaderSec.vue";
import Footer from "@/components/Homepage/FooterSec.vue";
import PyqSyPdf from "@/components/PYQ/PyqSyPdf.vue";
import TextTable from "@/components/PYQ/TextTable.vue";
import PyqOverview from "@/components/PYQ/PyqOverview.vue";
import PYQup from "@/components/PYQ/PYQup.vue";

export default {
  name: "SyllabusView",
  components: {
    Header,
    PYQup,
    PyqSyPdf,
    TextTable,
    PyqOverview,
    Footer,
  },
};
</script>

<style></style>

// trehousingpublications-main/frontend-react/src/views/PYQPageView.jsx
import React from 'react';
import Header from "../components/Homepage/HeaderSec.jsx";
import Footer from "../components/Homepage/FooterSec.jsx";
import PyqSyPdf from "../components/PYQ/PyqSyPdf.jsx";
import TextTable from "../components/PYQ/TextTable.jsx";
import PyqOverview from "../components/PYQ/PyqOverview.jsx";
import PYQup from "../components/PYQ/PYQup.jsx";
import BiharSyllabusComponent from "../components/PYQ/BiharSyllabusComponent.jsx";
import './PYQPageView.css';

export default function PYQPageView() {
  return (
    <div className="pyq-page-view">
      <Header />
      <PYQup />
      <PyqOverview />
      <TextTable />
      <BiharSyllabusComponent />
      <PyqSyPdf />
      <Footer />
    </div>
  );
}
