// frontend/src/views/SolvedPaperView.vue
<template>
  <Header />

 <TestSeriesHeroSection/>
  <HeaderDropdown />
  <downloadAttempt />
  <faq/>
  <R_M />
  <Footer />
</template>

<script>
import Header from "@/components/Homepage/HeaderSec.vue";
import Footer from "@/components/Homepage/FooterSec.vue";
import faq from'@/components/SolvedPaper/FAQ.vue';
import R_M from '@/components/SolvedPaper/Recomm_mock.vue'
import downloadAttempt from '@/components/SolvedPaper/DownloadAttempt.vue';
import HeaderDropdown from '@/components/SolvedPaper/HeaderDropdown.vue';

import TestSeriesHeroSection from '@/components/SolvedPaper/TestSeriesHeroSection.vue';
export default {
  name: "SolvedPaperView",
  components: {
    Header,
    faq,
    R_M,
    downloadAttempt,
    HeaderDropdown,
    TestSeriesHeroSection,

    Footer,
  },
};
</script>

<style></style>

// trehousingpublications-main/frontend-react/src/views/SolvedPaperView.jsx
import React from 'react';
import Header from "../components/Homepage/HeaderSec.jsx";
import Footer from "../components/Homepage/FooterSec.jsx";
import FAQ from '../components/SolvedPaper/FAQ.jsx';
import Recomm_mock from '../components/SolvedPaper/Recomm_mock.jsx';
import DownloadAttempt from '../components/SolvedPaper/DownloadAttempt.jsx';
import HeaderDropdown from '../components/SolvedPaper/HeaderDropdown.jsx';
import TestSeriesHeroSection from '../components/SolvedPaper/TestSeriesHeroSection.jsx';
import './SolvedPaperView.css';

export default function SolvedPaperView() {
  return (
    <div className="solved-paper-view">
      <Header />
      <TestSeriesHeroSection />
      <HeaderDropdown />
      <DownloadAttempt />
      <FAQ />
      <Recomm_mock />
      <Footer />
    </div>
  );
}
