// frontend/src/views/SyllabusView.vue
<template>
  <Header />
  <BctsExam />
  <RedTable />
  <SyllabusHigherSecondary />
  <SyllabusPdf />
  <Footer />
</template>

<script>
import Header from "@/components/Homepage/HeaderSec.vue";
import Footer from "@/components/Homepage/FooterSec.vue";

import SyllabusHigherSecondary from "@/components/Syllabus/SyllabusHigherSecondary.vue";

import SyllabusPdf from "@/components/Syllabus/syllabusPdf.vue";
import BctsExam from "@/components/Syllabus/BctsExam.vue";
import RedTable from "@/components/Syllabus/RedTable.vue";

export default {
  name: "SyllabusView",
  components: {
    Header,

    SyllabusPdf,
    RedTable,
    BctsExam,

    SyllabusHigherSecondary,
    Footer,
  },
};
</script>

<style></style>

// trehousingpublications-main/frontend-react/src/views/SyllabusView.jsx
import React from 'react';
import Header from "../components/Homepage/HeaderSec.jsx";
import Footer from "../components/Homepage/FooterSec.jsx";
import SyllabusHigherSecondary from "../components/syllabus/SyllabusHigherSecondary.jsx";
import SyllabusPdf from "../components/syllabus/syllabusPdf.jsx";
import BctsExam from "../components/syllabus/BctsExam.jsx";
import RedTable from "../components/syllabus/RedTable.jsx";
import './SyllabusView.css';

export default function SyllabusView() {
  return (
    <div className="syllabus-view">
      <Header />
      <BctsExam />
      <RedTable />
      <SyllabusHigherSecondary />
      <SyllabusPdf />
      <Footer />
    </div>
  );
}
