// trehousingpublications-main/frontend-react/src/views/TestSeriesView.jsx
import React from 'react';
import Header from "../components/Homepage/HeaderSec.jsx";
import Footer from "../components/Homepage/FooterSec.jsx";
import PopularTest from '../components/TestSeries/PopularTest.jsx';
import SeriesCategories from '../components/TestSeries/SeriesCategories.jsx';
import './TestSeriesView.css';

export default function TestSeriesView() {
  return (
    <div className="test-series-view">
      <Header />
      <PopularTest />
      <SeriesCategories />
      <Footer />
    </div>
  );
}

// frontend/src/views/TestSeriesView.vue
<template>
    <Header />
    <PopularTest />
    <SeriesCategories />
    <Footer />
</template>

<script>
import Header from "@/components/Homepage/HeaderSec.vue";
import Footer from "@/components/Homepage/FooterSec.vue";
import PopularTest from '@/components/TestSeries/PopularTest.vue';
import SeriesCategories from '@/components/TestSeries/SeriesCategories.vue';

export default{
    name : 'TestSeriesView',
    components : {
        Header,
        PopularTest,
        SeriesCategories,
        Footer,
    }
}
</script>
